version: "3.9"
services:
  web:
    image: "lewis150193/blog-node:v6"
    ports:
      - "5000:5000"
    depends_on:
      -  redis
    networks:
      - webnet
    environment:
      REDIS_URL: redis
    container_name: blog
  redis:
    image: 'redis'
    ports:
      - "6379:6379"
    networks:
      - webnet
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: redis

networks:
  webnet:
